export const listBks = [
  { id: 1, name: 'JPMorgan Chase', logo: 'https://i.imgur.com/OsPiDnc.png' },
  { id: 2, name: 'Bank of America', logo: 'https://i.imgur.com/Gj2VxwX.jpeg' },
  { id: 3, name: 'Wells Fargo', logo: 'https://i.imgur.com/xR1FYm0.jpeg' },
  { id: 4, name: 'Citibank', logo: 'https://i.imgur.com/Lz9cyNI.jpeg' },
  { id: 5, name: 'U.S. Bank', logo: 'https://i.imgur.com/p5A3hR7.jpeg' },
  { id: 6, name: 'Truist Bank', logo: 'https://i.imgur.com/iyU561P.jpeg' },
  { id: 7, name: 'PNC Bank', logo: 'https://i.imgur.com/PGDA88O.png' },
  { id: 8, name: 'TD Bank', logo: 'https://i.imgur.com/Udl94Me.jpeg' },
  { id: 9, name: 'Capital One', logo: 'https://i.imgur.com/3wLy50C.png' },
  { id: 10, name: 'HSBC Bank USA', logo: 'https://i.imgur.com/Mal8RKC.jpeg' },
  { id: 11, name: 'Goldman Sachs', logo: 'https://i.imgur.com/eCs0aoi.jpeg' },
  { id: 12, name: 'Morgan Stanley', logo: 'https://i.imgur.com/RfBAJ0H.jpeg' },
  { id: 13, name: 'American Express', logo: 'https://i.imgur.com/SjTIG33.png' },
  { id: 14, name: 'Charles Schwab', logo: 'https://i.imgur.com/0iY3fGx.png' },
  { id: 15, name: 'Fifth Third Bank', logo: 'https://i.imgur.com/v1r65b2.jpeg' },
  { id: 16, name: 'BBVA USA', logo: 'https://i.imgur.com/BEiHg5s.jpeg' },
  { id: 17, name: 'Ally Bank', logo: 'https://i.imgur.com/m6qu8jy.jpeg' },
  { id: 18, name: 'Regions Bank', logo: 'https://i.imgur.com/NDiSZCv.jpeg' },
  { id: 19, name: 'Huntington Bank', logo: 'https://i.imgur.com/K6DcOhV.jpeg' },
  { id: 20, name: 'KeyBank', logo: 'https://i.imgur.com/ActdEz4.png' },
  { id: 21, name: 'Citizens Bank', logo: 'https://i.imgur.com/cFYhhbQ.jpeg' },
  { id: 22, name: 'First Republic Bank', logo: 'https://i.imgur.com/T7VNWea.png' },
  { id: 23, name: 'BMO Harris Bank', logo: 'https://i.imgur.com/5rmRHsL.jpeg' },
  { id: 24, name: 'Bank of the West', logo: 'https://i.imgur.com/r3teXIP.png' },
  { id: 25, name: 'Synchrony Bank', logo: 'https://i.imgur.com/vdAEawF.png' },
  { id: 26, name: 'Barclays Bank', logo: 'https://i.imgur.com/8HhN6ZV.png' },
  { id: 27, name: 'Northern Trust', logo: 'https://i.imgur.com/Da7p1Fs.png' },
  { id: 28, name: 'Santander Bank', logo: 'https://i.imgur.com/PAL2WFa.jpeg' },
  { id: 29, name: 'BNY Mellon', logo: 'https://i.imgur.com/5miDK69.jpeg' },
  { id: 30, name: 'HSBC UK', logo: 'https://i.imgur.com/Mal8RKC.jpeg' },
  { id: 31, name: 'Lloyds Bank', logo: 'https://i.imgur.com/5rmRHsL.jpeg' },
  { id: 32, name: 'NatWest', logo: 'https://i.imgur.com/cFYhhbQ.jpeg' },
  { id: 33, name: 'Royal Bank of Scotland', logo: 'https://i.imgur.com/T7VNWea.png' },
  { id: 34, name: 'Santander UK', logo: 'https://i.imgur.com/PAL2WFa.jpeg' },
  { id: 35, name: 'Nationwide Building Society', logo: 'https://i.imgur.com/vdAEawF.png' },
  { id: 36, name: 'TSB Bank', logo: 'https://i.imgur.com/r3teXIP.png' },
  { id: 37, name: 'Metro Bank', logo: 'https://i.imgur.com/v1r65b2.jpeg' },
  { id: 38, name: 'Virgin Money UK', logo: 'https://i.imgur.com/SjTIG33.png' },
  { id: 39, name: 'Monzo Bank', logo: 'https://i.imgur.com/0iY3fGx.png' },
  { id: 40, name: 'Starling Bank', logo: 'https://i.imgur.com/m6qu8jy.jpeg' },
  { id: 41, name: 'Clydesdale Bank', logo: 'https://i.imgur.com/ActdEz4.png' },
  { id: 42, name: 'The Co-operative Bank', logo: 'https://i.imgur.com/NDiSZCv.jpeg' },
  { id: 43, name: 'Bank of Scotland', logo: 'https://i.imgur.com/5miDK69.jpeg' },
  { id: 44, name: 'Yorkshire Bank', logo: 'https://i.imgur.com/QMFFZyc.png' },
  { id: 45, name: 'Handelsbanken UK', logo: 'https://i.imgur.com/z8gLs8F.png' },
  { id: 46, name: 'Aldermore Bank', logo: 'https://i.imgur.com/NwcNhCn.png' },
  { id: 47, name: 'Close Brothers', logo: 'https://i.imgur.com/jqPEjKU.png' },
  { id: 48, name: 'Shawbrook Bank', logo: 'https://i.imgur.com/3lDAlxV.png' },
  { id: 49, name: 'Atom Bank', logo: 'https://i.imgur.com/W69OXm2.png' },
  { id: 50, name: 'Tide', logo: 'https://i.imgur.com/QDHyWyl.png' },
  { id: 51, name: 'Triodos Bank', logo: 'https://i.imgur.com/QYlgd2x.png' },
  { id: 52, name: 'Charity Bank', logo: 'https://i.imgur.com/3zzLhZT.png' },
  { id: 53, name: 'OneSavings Bank', logo: 'https://i.imgur.com/XFMPFtt.png' },
  { id: 54, name: 'Tesco Bank', logo: 'https://i.imgur.com/tZ2BLTG.png' },
  { id: 55, name: "Sainsbury's Bank", logo: 'https://i.imgur.com/UpMiR8g.png' },
  { id: 56, name: 'Bank of Ireland UK', logo: 'https://i.imgur.com/LJ6x2UP.png' },
  { id: 57, name: 'Paragon Bank', logo: 'https://i.imgur.com/lLYUn5V.png' },
  { id: 58, name: 'Coventry Building Society', logo: 'https://i.imgur.com/n1OOsK2.png' }
];
